package Daje::Workflow::Database::Connector;




1;







#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Workflow::Database::Connector




=head1 REQUIRES


Daje::Workflow::Database::Model::Context>

Daje::Workflow::Database::Model::Workflow>

Mojo::Base>




=head1 METHODS


 load($self)

 load_context($self)

 load_workflow($self)

 save_context($self)

 save_workflow($self)

 start($self)

 stop($self,



=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.comE<gt>



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

